### ISSUE TITLE
data can't equal rules all time mr

### ISSUE THREAD

**Issue by ahmedtofaha10** [AhmedJoda/joda-resources#1]
## rules 
can't depends on rules to get data every time please make something new  
``` diff
 - $data = Validate(........
 + $this->validate(.......
 + $data = request()-excepts($excepts); # or any thing similar 
```
**thanks**

**Comment by ahmedalmory** [comment]
One of the important factors I take into account while developing the package is security, you should type all expected data for security reasons.


For more information read this

https://github.com/alexeymezenin/laravel-best-practices/issues/22
